### ISSUE TITLE
how to using url image 

### ISSUE THREAD

**Issue by thandonguocmo2020** [VinceG/laravel-angular#2]
how to using  URL image in file *.component.html.
Help !

**Comment by VinceG** [comment]
@thandonguocmo2020 you should try and ask at the laravel forums. this repository is more of an example of how to use Laravel with Angular.

**Comment by thandonguocmo2020** [comment]
I found it and then put dist css and js and image there. 

resources/asset/src/public/

Image in laravel I set off into static route.

Thank you for developing it

**Comment by VinceG** [comment]
@thandonguocmo2020 thank you for trying.
