### ISSUE TITLE
angular-cli

### ISSUE THREAD

**Issue by num3r06** [VinceG/laravel-angular#3]
Hi, great job
It's possbile to use angular-cli for generate component?
Or which method you use for generate new angular component in a src folder? Manually?

**Comment by VinceG** [comment]
Yes I just generated them manually for this example 

-----
Vincent Gabriel
Software Engineer

Please excuse my brevity, sent from my iPhone

**Comment by VinceG** [comment]
@num3r06

**Comment by num3r06** [comment]
Ok thx. If you have a method for using angular-cli in this repo you can send me a msg
